### ISSUE TITLE
Add responsive horizontal scroll to anime cards

### ISSUE THREAD

**Issue by mubashir-rehman** [abdullah-ch/Anime-WebApp#2]
Issue:
Currently, when mouse hovered before first card of the container (top anime container list) or last card in the view (say 5th) it starts a vibrating effect rather than doing nothing or moving the 6th card into view, resoectively.

Possible Solution:
https://stackoverflow.com/questions/30495062/how-can-i-scroll-a-div-to-be-visible-in-reactjs
https://stackoverflow.com/questions/51887928/horizontal-auto-scroll-to-a-react-component

**Comment by abdullah-ch** [comment]
Good eye, Mubashir. Thanks for opening the issue. I have fixed this now (I think). Please check the app again and give me your feedback. I'll close the issue when you're satisfied. Waiting for your response !

**Comment by mubashir-rehman** [comment]
It works smooth. However, the card hover animation looks weird on my phone. The Red box losses one side on my nexus 6p using Chrome android.

**Comment by abdullah-ch** [comment]
I am afraid this I can't change as I have styled the app keeping in mind the average width of mobile phones. Meaning, app can vary display to display.

**Comment by abdullah-ch** [comment]
Now, I am closing this, you can contact me whenever you want !
